#!/bin/bash
#!/bin/sh

#
# chkconfig: 35 99 99
# description: Node.js /home/nodejs/sample/app.js
#

. /etc/rc.d/init.d/functions

USER="root"

DAEMON="/usr/bin/node"
ROOT_DIR="/var/www/api"
SERVER="$ROOT_DIR/index.js"
LOG_FILE="$ROOT_DIR/index.js.log"

LOCK_FILE="/var/lock/subsys/node-server"

do_stop()
{
        echo -n $"Stopping $SERVER: "
        pid=`ps -aefw | grep "$DAEMON $SERVER" | grep -v " grep " | awk '{print $2}'`
        if [ -z "$pid" ]
        then
                RETVAL=0
                echo "Server already Stopped"
        else
                kill -9 $pid > /dev/null 2>&1 && echo_success || echo_failure
                RETVAL=$?
                echo
        fi
        [ $RETVAL -eq 0 ] && rm -f $LOCK_FILE
}

case "$1" in
        *)
                do_stop
                ;;
esac

exit $RETVAL
